name: Deploy
on:
  push:
    branches:
      - master

jobs:
  detect-changes:
    runs-on: self-hosted
    outputs:
      calculadora-ris3cat_changed: ${{ steps.check_calculadora-ris3cat.outputs.changed }}
      wiki-ris3cat_changed: ${{ steps.check_wiki-ris3cat.outputs.changed }}
      api-ris3cat_changed: ${{ steps.check_api-ris3cat.outputs.changed }}
    steps:
      - name: Pull changes
        run: |
          cd /home/megatro/apps/dockers/Ris3Cat/zertipower-zertibuilder
          echo "Pulling and rebasing changes from github"
          git pull --rebase

      
      - name: Detect changes in calculadora-ris3cat
        id: check_calculadora-ris3cat
        run: |
          cd /home/megatro/apps/dockers/Ris3Cat/zertipower-zertibuilder
          cd frontend
          echo "Getting calculadora-ris3cat diff"
          CHANGED_FILES=$(git diff --name-only HEAD HEAD~1 | grep "^frontend/" || true)
          echo "Checking calculadora-ris3cat diff"
          if [ -n "$CHANGED_FILES" ]; then
            echo "Changes detected in calculadora-ris3cat"
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "No changes in calculadora-ris3cat"
            echo "changed=false" >> $GITHUB_OUTPUT
          fi

      
      - name: Detect changes in wiki-ris3cat
        id: check_wiki-ris3cat
        run: |
          cd /home/megatro/apps/dockers/Ris3Cat/zertipower-zertibuilder
          cd zertipower-hugo
          echo "Getting wiki-ris3cat diff"
          CHANGED_FILES=$(git diff --name-only HEAD HEAD~1 | grep "^zertipower-hugo/" || true)
          echo "Checking wiki-ris3cat diff"
          if [ -n "$CHANGED_FILES" ]; then
            echo "Changes detected in wiki-ris3cat"
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "No changes in wiki-ris3cat"
            echo "changed=false" >> $GITHUB_OUTPUT
          fi

      
      - name: Detect changes in api-ris3cat
        id: check_api-ris3cat
        run: |
          cd /home/megatro/apps/dockers/Ris3Cat/zertipower-zertibuilder
          cd backend
          echo "Getting api-ris3cat diff"
          CHANGED_FILES=$(git diff --name-only HEAD HEAD~1 | grep "^backend/" || true)
          echo "Checking api-ris3cat diff"
          if [ -n "$CHANGED_FILES" ]; then
            echo "Changes detected in api-ris3cat"
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "No changes in api-ris3cat"
            echo "changed=false" >> $GITHUB_OUTPUT
          fi

      

  
  deploy-calculadora-ris3cat:
      needs: detect-changes
      runs-on: self-hosted
      steps:
        - name: Deploy calculadora-ris3cat if changed
          if: needs.detect-changes.outputs.calculadora-ris3cat_changed == 'true'
          run: |
            cd /home/megatro/apps/dockers/Ris3Cat/zertipower-zertibuilder
            echo "Deploying calculadora-ris3cat"
            cd frontend
            npm i
            npm run build
            docker compose up -d calculadora-ris3cat --build --force-recreate
            echo "calculadora-ris3cat deployed"
  
  deploy-wiki-ris3cat:
      needs: detect-changes
      runs-on: self-hosted
      steps:
        - name: Deploy wiki-ris3cat if changed
          if: needs.detect-changes.outputs.wiki-ris3cat_changed == 'true'
          run: |
            cd /home/megatro/apps/dockers/Ris3Cat/zertipower-zertibuilder
            echo "Deploying wiki-ris3cat"
            cd zertipower-hugo
            npm i
            hugo
            docker compose up -d wiki-ris3cat --build --force-recreate
            echo "wiki-ris3cat deployed"
  
  deploy-api-ris3cat:
      needs: detect-changes
      runs-on: self-hosted
      steps:
        - name: Deploy api-ris3cat if changed
          if: needs.detect-changes.outputs.api-ris3cat_changed == 'true'
          run: |
            cd /home/megatro/apps/dockers/Ris3Cat/zertipower-zertibuilder
            echo "Deploying api-ris3cat"
            cd backend
            npm i
            npx prisma generate
            docker compose up -d api-ris3cat --build --force-recreate
            echo "api-ris3cat deployed"
