name: Deploy
on:
  push:
    branches:
      - master

jobs:
  detect-changes:
    runs-on: self-hosted
    outputs:
      calculadora_changed: ${{ steps.check_calculadora.outputs.changed }}
      wiki_changed: ${{ steps.check_wiki.outputs.changed }}
      api_changed: ${{ steps.check_api.outputs.changed }}
    steps:
      - name: Pull changes
        run: |
          cd /home/megatro/apps/dockers/Ris3Cat/zertipower-zertibuilder
          git switch master
          LAST_COMMIT=$(git rev-parse HEAD) # Getting last commit before changes
          echo "Pulling and rebasing changes from github"
          git pull --rebase origin master
          echo "LAST_COMMIT=${LAST_COMMIT}" >> $GITHUB_ENV

      
      - name: Detect changes in calculadora
        id: check_calculadora
        run: |
          cd /home/megatro/apps/dockers/Ris3Cat/zertipower-zertibuilder
          cd frontend
          echo "Getting calculadora diff"
          CHANGED_FILES=$(git diff --name-only HEAD $LAST_COMMIT | grep "^frontend/" || true)
          echo "Checking calculadora diff"
          if [ -n "$CHANGED_FILES" ]; then
            echo "Changes detected in calculadora"
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "No changes in calculadora"
            echo "changed=false" >> $GITHUB_OUTPUT
          fi

      
      - name: Detect changes in wiki
        id: check_wiki
        run: |
          cd /home/megatro/apps/dockers/Ris3Cat/zertipower-zertibuilder
          cd zertipower-hugo
          echo "Getting wiki-ris3cat diff"
          CHANGED_FILES=$(git diff --name-only HEAD $LAST_COMMIT | grep "^zertipower-hugo/" || true)
          echo "Checking wiki-ris3cat diff"
          if [ -n "$CHANGED_FILES" ]; then
            echo "Changes detected in wiki-ris3cat"
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "No changes in wiki-ris3cat"
            echo "changed=false" >> $GITHUB_OUTPUT
          fi

      
      - name: Detect changes in api
        id: check_api
        run: |
          cd /home/megatro/apps/dockers/Ris3Cat/zertipower-zertibuilder
          cd backend
          echo "Getting api-ris3cat diff"
          CHANGED_FILES=$(git diff --name-only HEAD $LAST_COMMIT | grep "^backend/" || true)
          echo "Checking api-ris3cat diff"
          if [ -n "$CHANGED_FILES" ]; then
            echo "Changes detected in api-ris3cat"
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "No changes in api-ris3cat"
            echo "changed=false" >> $GITHUB_OUTPUT
          fi

      

  
  deploy-calculadora:
      needs: detect-changes
      runs-on: self-hosted
      steps:
        - name: Deploy calculadora-ris3cat if changed
          if: needs.detect-changes.outputs.calculadora_changed == 'true'
          run: |
            cd /home/megatro/apps/dockers/Ris3Cat/zertipower-zertibuilder
            echo "Deploying calculadora"
            cd frontend
            npm i
            npm run build
            docker compose up -d calculadora-ris3cat --build --force-recreate
            echo "calculadora-ris3cat deployed"
  
  deploy-wiki:
      needs: detect-changes
      runs-on: self-hosted
      steps:
        - name: Deploy wiki-ris3cat if changed
          if: needs.detect-changes.outputs.wiki_changed == 'true'
          run: |
            cd /home/megatro/apps/dockers/Ris3Cat/zertipower-zertibuilder
            echo "Deploying wiki-ris3cat"
            cd zertipower-hugo
            npm i
            hugo
            docker compose up -d wiki-ris3cat --build --force-recreate
            echo "wiki-ris3cat deployed"
  
  deploy-api:
      needs: detect-changes
      runs-on: self-hosted
      steps:
        - name: Deploy api-ris3cat if changed
          if: needs.detect-changes.outputs.api_changed == 'true'
          run: |
            cd /home/megatro/apps/dockers/Ris3Cat/zertipower-zertibuilder
            echo "Deploying api"
            cd backend
            npm i
            npx prisma generate
            docker compose up -d api-ris3cat --build --force-recreate
            echo "api-ris3cat deployed"
